routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'checklanguage'], function () {
	Route::get('/', function () {
		return redirect('/login');
	});

	Auth::routes();
	Route::post('/change_lang', 'ChangeLanguageController@changeLang')->name('change_lang');
	Route::group(['middleware' => 'auth'], function () {
		Route::get('/home', 'HomeController@index')->name('home');
		Route::resources([
			'companies' => 'CompanyController',
			'employees' => 'EmployeeController'
		]);
	});
});

app/Company.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Company extends Model {
}

app/Http/Controllers/CompanyController.php
<?php
namespace App\Http\Controllers;
use App\Company;
use Illuminate\Http\Request;
class CompanyController extends Controller {
    public function __construct() {
        $this->middleware('auth');
    }
    public function index() {
        $data = [];
        $data['companies'] = Company::orderby('created_at', 'DESC')->paginate(10);
        return view('companies.index')->with($data);
    }
    public function create() {
        return view('companies.create');
    }
    public function store(Request $request) {
        $request_payload_required = [
            'name'    => 'required|min:3',
            'website' => 'required|url',
            'email'   => 'required|string|email|unique:companies',
            'logo'    => 'required|image|mimes:jpeg,png,jpg|dimensions:max_width=100px,max_height=100px'
        ];
        \Validator::make($request->all(), $request_payload_required)->validate();
        try{
            \DB::beginTransaction();
            $get = new Company;
            if($get){
                $get->name = $request->get('name');
                $get->email = $request->get('email');
                $get->website = $request->get('website');
                if($request->hasFile('logo')){
                    $content = file_get_contents($request->file('logo')->getRealPath());
                    $rename = basename(preg_replace("/[^A-Za-z0-9\_\-\.]/", '', $request->file('logo')->getClientOriginalName()));
                    \Storage::disk('local')->put('public/'.$rename, $content, 'public');
                    $get->logo = $rename;
                }
                $get->save();
                $get = $get->toArray();
                $content = str_replace(':name', $get['name'], __('sentence.email_text'));
                $content = str_replace(':email', $get['email'], $content);
                \Mail::send(array(), $get, function ($message) use ($get, $content) {
                    $message->to($get['email'], $get['name'])
                    ->subject(__('sentence.comapny_registration_success'))
                    ->setBody($content, 'text/html');
                });
            }
            \DB::commit();
            set_msg_session('company_creation', 'new_company_record_created_successfully', '', 'success');
            return redirect()->route('companies.index');
        } catch (\Exception $e) {
            \DB::rollBack();
            dd($e);
            set_msg_session('company_creation', 'new_company_record_creation_fail_try_again' , "", 'error');
            catch_exception($e);
            return back()
            ->withInput();
        }
    }
    public function show(Company $company) {
    }
    public function edit($id) {
        $data = array();
        $id = get_secure_id($id);
        $data['data'] = Company::find($id);
        return view('companies.create')->with($data);
    }
    public function update(Request $request, $id) {
        $id = get_secure_id($id);
        $get = Company::find($id);
        $request_payload_required = [
            'name' => 'required|min:3',
            'website' => 'required|url',
            'email' => 'required|string|email|unique:companies,email,'.$get->id,
        ];
        if($request->hasFile('logo')) {
            $request_payload_required['logo'] = 'required|image|mimes:jpeg,png,jpg|dimensions:max_width=100px,max_height=100px';
        }
        elseif($request->get('old_logo') != '') {
            if(!(\Storage::disk('local')->exists('public/'.basename($request->get('old_logo'))))) {
                $request_payload_required['logo'] = 'required|image|mimes:jpeg,png,jpg|dimensions:max_width=100px,max_height=100px';
            }
        } else {
            $request_payload_required['logo'] = 'required|image|mimes:jpeg,png,jpg|dimensions:max_width=100px,max_height=100px';
        }
        \Validator::make($request->all(), $request_payload_required)->validate();
        try{
            \DB::beginTransaction();
            if($get) {
                $get->name = $request->get('name');
                $get->email = $request->get('email');
                $get->website = $request->get('website');
                if($request->hasFile('logo')) {
                    $content = file_get_contents($request->file('logo')->getRealPath());
                    $rename = basename(preg_replace("/[^A-Za-z0-9\_\-\.]/", '', $request->file('logo')->getClientOriginalName()));
                    \Storage::disk('local')->put('public/'.$rename, $content, 'public');
                    $get->logo = $rename;
                } else {
                    $get->logo = basename($request->get('old_logo'));
                }
                $get->save();
            }
            \DB::commit();
            set_msg_session('company_updation', 'company_record_updated_successfully', '', 'success');
            return redirect()->route('companies.index');
        } catch (\Exception $e) {
            \DB::rollBack();
            dd($e);
            set_msg_session('company_updation', 'company_record_update_fail_try_again' , "", 'error');
            catch_exception($e);
            return back()
            ->withInput();
        }
    }
    public function destroy($id) {
        try{
            \DB::beginTransaction();
            $id = get_secure_id($id);
            $get = Company::find($id);
            if($get) {
                $get->delete();
            }
            \DB::commit();
            set_msg_session('company_updation', 'company_record_deleted' , "", 'success');
            return redirect()->route('companies.index');
        } catch (\Exception $e) {
            \DB::rollBack();
            set_msg_session('company_updation', 'company_record_deletion_fail_try_again' , "", 'error');
            catch_exception($e);
            return back()
            ->withInput();
        }
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-12">
			<div class="card">
				@if(isset($data))
				<div class="card-header">{{ __('sentence.edit_company') }} <b>{{ $data->name }}</b>
					@else
					<div class="card-header">{{ __('sentence.create_new_company') }}
						@endif
					</div>
					<div class="card-body">
						<h6 class="card-subtitle"> {!! __('sentence.all_fields_marked_with_asterisk_are_required') !!}. </h6>
						<br>
						@if (isset($errors) && $errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach ($errors->all() as $error)
								<li>{{ __($error) }}</li>
								@endforeach
							</ul>
						</div>
						@endif
						@if(isset($data))
						<form enctype="multipart/form-data" class="form_form m-t-40" method="post" action="{{ route('companies.update', set_secure_id($data->id)) }}" novalidate>
							<input type="hidden" name="edit_id" value="{{ set_secure_id($data->id) }}">
							{!! csrf_field() !!}
							@method('PUT')
							@else
							<form enctype="multipart/form-data" class="form_form m-t-40" method="post" action="{{ route('companies.store') }}" novalidate>
								{!! csrf_field() !!}
								@endif
								<div class="p-t-10">
									<div class="form-group">
										<label>{{ __('sentence.name') }} <span class="text-danger"> *</span></label>
										<input name="name" type="text" class="form-control" value="{{ old('name') ?? $data->name ?? '' }}">
									</div>
									<div class="form-group">
										<label>{{ __('sentence.email') }} <span class="text-danger"> *</span></label>
										<input name="email" type="text" class="form-control" value="{{ old('email') ?? $data->email ?? '' }}">
									</div>
									<div class="form-group">
										<label>{{ __('sentence.website') }} <span class="text-danger"> *</span></label>
										<input name="website" type="text" class="form-control" value="{{ old('website') ?? $data->website ?? '' }}" placeholder="http://www.example.com | https://www.example.com">
									</div>
									<div class="form-group col-md-5 d-inline-block p-0 align-top">
										<label>{{ __('sentence.logo') }} <span class="text-danger"> *</span><br><small><span class="text-danger">{{ __('sentence.max_allowed_size') }} 100X100</span></small></label>
										<input type='file' name="logo" id="imgInp" class="form-control">
										<input type='hidden' name="old_logo" id="" class="old_logo" value="{{ (isset($data->logo)) ? asset('storage/'.$data->logo) : '' }}">
									</div>
									<div class="form-group col-md-5 d-inline-block" style="margin-left: 100px;">
										@if(old('logo') != null || (!empty($data->logo) && \Storage::disk('local')->exists('public/'.$data->logo)))
										<img id="img_preview_old" class="img_pre_old" src="{{ old('logo') ?? $data->logo ? asset('storage/'.$data->logo) : '' }}" alt="{{ __('sentence.your_image') }}" style="width: 100px; height: 100px;" />
										<br>
										<span class="img_pre_old"> {{ __('sentence.your_uploaded_image') }}</span>
										<img id="img_preview" class="img_pre d-none" src="" alt="{{ __('sentence.your_image') }}" style="width: 100px; height: 100px;" />
										<br>
										<span class="img_pre d-none"> {{ __('sentence.new_image') }}</span>
										@else
										<img id="img_preview" class="img_pre d-none" src="" alt="{{ __('sentence.your_image') }}" style="width: 100px; height: 100px;" />
										<br>
										<span class="img_pre d-none"> {{ __('sentence.new_image') }}</span>
										@endif
									</div>
								</div>
								<div class="form-group">
									<button type="submit" class="btn btn-primary">{{ __('sentence.submit') }}</button>
									&nbsp;&nbsp;&nbsp;&nbsp;
									<a href="{{ url()->previous() }}" class="btn btn-light"><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp; {{ __('sentence.go_back') }}</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">@lang('sentence.all_companies')</div>
				<div class="card-body">
					@if (session('status'))
					<div class="alert alert-{{ session('message_type') }}" role="alert">
						{{ session('status') }}
					</div>
					@endif
					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover table-sm">
							<caption>{{ __('sentence.list_of_companies') }}</caption>
							<thead class="thead-light">
								<tr>
									<th>#</th>
									<th>{{ __('sentence.company_name') }}</th>
									<th>{{ __('sentence.company_email') }}</th>
									<th>{{ __('sentence.company_website') }}</th>
									<th>{{ __('sentence.company_logo') }}</th>
									<th>{{ __('sentence.actions') }}</th>
								</tr>
							</thead>
							<tbody>
								@foreach($companies as $company)
								<tr>
									<td>{{ ++$loop->index }}</td>
									<td>{{ $company->name }}</td>
									<td>{{ $company->email }}</td>
									<td>{{ $company->website }}</td>
									<td>
										@if(!empty($company->logo))
										<a href="javascript:;" data-toggle='modal' data-target='#myModal-{{ $company->id }}' title="{{ __('sentence.click_to_preview_logo') }}"><img src="{{ asset('storage/'.$company->logo) }}" alt="{{ __('sentence.dummy_image') }}"></a>
										@include('companies.includes.details')
										@else
										{{ __('sentence.no_logo_present') }}
										@endif
									</td>
									<td>
										<a href="{{ route('companies.edit', set_secure_id($company->id)) }}" title='{{ __('sentence.edit') }}'>
											<button type='button' class='btn btn-xs btn-warning'>
												<i class='fa fa-edit'></i>
											</button>
										</a>
										<a title='{{ __('sentence.delete') }}' class='company-delete' data-form_id='company-delete-{{ set_secure_id($company->id) }}'>
											<button type='button' class='btn btn-xs btn-danger'>
												<i class='fa fa-trash trash'></i>
											</button>
										</a>
										<form id='company-delete-{{ set_secure_id($company->id) }}' action="{{ route('companies.destroy', set_secure_id($company->id)) }}" method='POST' style='display: none;'>
											{!! csrf_field() !!}
											@method('DELETE')
											<input type='hidden' name='delete_id' value="{{ set_secure_id($company->id) }}">
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
						{{ $companies->links() }}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection